chanallege
1. Data preprocessing

**1. Data Preprocessing**

In [48]:
import pandas as pd

# Load the datasets
df_health_1 = pd.read_csv('/content/health.csv')
df_health_2 = pd.read_csv('/content/dataset2.csv')

In [49]:
# check the missing values
print(df_health_1.isnull().sum())
print(df_health_2.isnull().sum())

Patient_Number                      0
Blood_Pressure_Abnormality          0
Level_of_Hemoglobin                 0
Genetic_Pedigree_Coefficient       92
Age                                 0
BMI                                 0
Sex                                 0
Pregnancy                        1558
Smoking                             0
salt_content_in_the_diet            0
alcohol_consumption_per_day       242
Level_of_Stress                     0
Chronic_kidney_disease              0
Adrenal_and_thyroid_disorders       0
dtype: int64
Patient_Number          0
Day_Number              0
Physical_activity    3841
dtype: int64

In [50]:
df_health_1.shape # shape of the dataset

(2000, 14)

In [51]:
# if the sex is 0(Male) then pregnancy 0(N0)
df_health_1.loc[df_health_1['Sex'] == 0, 'Pregnancy'] = 0

In [52]:
# if the age is greter then 45, than pregnancy 0(N0)
df_health_1.loc[df_health_1['Age'] >= 45, 'Pregnancy'] = 0

In [53]:
# convert the float into integer
df_health_1['Pregnancy']=df_health_1['Pregnancy'].astype(int)

In [54]:
df_health_1.head()

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,0.90,34,23,1,1,0,48071,NaN,2,1,1
1,2,0,9.75,0.23,54,33,1,0,0,25333,205.0,3,0,0
2,3,1,10.79,0.91,70,49,0,0,0,29465,67.0,2,1,0
3,4,0,11.00,0.43,71,50,0,0,0,7439,242.0,1,0,0
4,5,1,14.17,0.83,52,19,0,0,0,49644,397.0,2,0,0

In [55]:
# Genetic_Pedigree_Coefficient is less then 0.5 are equal to 0, greater then 0.5 equal to 1
df_health_1['Genetic_Pedigree_Coefficient'] = df_health_1['Genetic_Pedigree_Coefficient'].apply(lambda x: 0 if x < 0.5 else 1)

In [56]:
# In alcohol_consumption_per_day null values are fill with 0
df_health_1['alcohol_consumption_per_day'].fillna(0, inplace=True)

In [57]:
# convert the float into integer
df_health_1['alcohol_consumption_per_day']=df_health_1['alcohol_consumption_per_day'].astype(int)

In [58]:
# check the duplicate
df_health_1['Patient_Number'].duplicated().sum()

0

In [59]:
# Group the patient number and fill with average Physical_activity
df_health_2['Physical_activity'] = df_health_2.groupby('Patient_Number')['Physical_activity'].transform(lambda x: x.fillna(x.mean()))

In [60]:
df_health_2.shape

(20000, 3)

In [61]:
print(df_health_1.isnull().sum())
print(df_health_2.isnull().sum())

Patient_Number                   0
Blood_Pressure_Abnormality       0
Level_of_Hemoglobin              0
Genetic_Pedigree_Coefficient     0
Age                              0
BMI                              0
Sex                              0
Pregnancy                        0
Smoking                          0
salt_content_in_the_diet         0
alcohol_consumption_per_day      0
Level_of_Stress                  0
Chronic_kidney_disease           0
Adrenal_and_thyroid_disorders    0
dtype: int64
Patient_Number       0
Day_Number           0
Physical_activity    0
dtype: int64

In [65]:
df_health_1.head(20)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,11.28,1,34,23,1,1,0,48071,0,2,1,1
1,2,0,9.75,0,54,33,1,0,0,25333,205,3,0,0
2,3,1,10.79,1,70,49,0,0,0,29465,67,2,1,0
3,4,0,11.00,0,71,50,0,0,0,7439,242,1,0,0
4,5,1,14.17,1,52,19,0,0,0,49644,397,2,0,0
5,6,0,11.64,1,23,48,0,0,1,7513,0,3,0,0
6,7,1,11.69,1,43,41,1,1,0,32967,206,3,1,1
7,8,0,12.70,0,48,20,0,0,0,26749,134,2,0,0
8,9,0,10.88,1,72,44,0,0,0,9607,99,3,0,0
9,10,1,14.56,1,40,44,0,0,0,12715,95,2,0,0
10,11,1,8.58,0,70,28,1,0,0,26178,46,1,1,1
11,12,1,12.77,0,35,17,0,0,0,43040,382,3,1,0
12,13,1,16.40,0,31,50,0,0,1,46997,41,3,0,1
13,14,0,16.42,0,75,40,0,0,1,49800,308,3,0,0
14,15,0,11.97,1,18,32,0,0,0,18007,0,2,0,0
15,16,1,10.96,0,43,27,1,1,0,39018,495,1,1,0
16,17,1,11.98,0,65,28,1,0,0,45217,377,2,0,0
17,18,1,11.60,0,61,44,0,0,0,36987,153,2,0,0
18,19,1,8.99,0,18,30,1,1,0,35603,0,3,1,0
19,20,1,16.55,1,18,38,0,0,0,1807,0,3,1,1

In [ ]:
normalization
#salt_content_in_the_diet,Level_of_Hemoglobin,BMI,alcohol_consumption_per_day

In [66]:
df_health_1.columns

Index(['Patient_Number', 'Blood_Pressure_Abnormality', 'Level_of_Hemoglobin',
       'Genetic_Pedigree_Coefficient', 'Age', 'BMI', 'Sex', 'Pregnancy',
       'Smoking', 'salt_content_in_the_diet', 'alcohol_consumption_per_day',
       'Level_of_Stress', 'Chronic_kidney_disease',
       'Adrenal_and_thyroid_disorders'],
      dtype='object')

**2. Retrieval-Augmented Generation (RAG) Model**

(a) Data Retrieval using FAISS:

In [76]:
import faiss
import numpy as np

# Indexing Health Dataset 1 for quick retrieval
health_data_matrix = df_health_1[['Patient_Number']].values.astype(np.float32)

# Initialize the FAISS index
index = faiss.IndexFlatL2(health_data_matrix.shape[1])
index.add(health_data_matrix)

# Function to search for similar records
def search_health_data(query_vector, k=5):
    query_vector = np.array(query_vector).astype(np.float32).reshape(1, -1)
    _, indices = index.search(query_vector, k)
    return df_health_1.iloc[indices[0]]

# Example: Search for records similar to a specific vector
query = [9]
result = search_health_data(query)
print(result)

    Patient_Number  Blood_Pressure_Abnormality  Level_of_Hemoglobin  \
8                9                           0                10.88
7                8                           0                12.70
9               10                           1                14.56
6                7                           1                11.69
10              11                           1                 8.58

    Genetic_Pedigree_Coefficient  Age  BMI  Sex  Pregnancy  Smoking  \
8                              1   72   44    0          0        0
7                              0   48   20    0          0        0
9                              1   40   44    0          0        0
6                              1   43   41    1          1        0
10                             0   70   28    1          0        0

    salt_content_in_the_diet  alcohol_consumption_per_day  Level_of_Stress  \
8                       9607                           99                3
7                      26749                          134                2
9                      12715                           95                2
6                      32967                          206                3
10                     26178                           46                1

    Chronic_kidney_disease  Adrenal_and_thyroid_disorders
8                        0                              0
7                        0                              0
9                        0                              0
6                        1                              1
10                       1                              1

In [69]:
!pip install faiss-cpu

Collecting faiss-cpu
  Downloading faiss_cpu-1.8.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Requirement already satisfied: numpy<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from faiss-cpu) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from faiss-cpu) (24.1)
Downloading faiss_cpu-1.8.0.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 35.5 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.8.0.post1

(b) Generative Model Integration:

In [74]:
from transformers import T5Tokenizer, T5ForConditionalGeneration

# Load pre-trained T5 model and tokenizer
tokenizer = T5Tokenizer.from_pretrained('t5-small')
model = T5ForConditionalGeneration.from_pretrained('t5-small')

# Define a function to generate a response
def generate_response(health_data, query):
    input_text = f"Generate a health insight based on: {health_data} and query: {query}"
    inputs = tokenizer.encode(input_text, return_tensors='pt', max_length=512, truncation=True)

    outputs = model.generate(inputs, max_length=1500, num_beams=5, early_stopping=True)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

'Patient_Number': 5.0, 'Blood_Pressure_Abnormality': 1.0, 'Level_of_Hemoglobin': 14.17, 'Genetic_Pedigree_Coefficient': 1.0, 'Age': 52.0, 'BMI': 19.0, 'Sex': 0.0, 'Smoking': 0.0,'salt_content_in_

In [79]:
# Example usage: Pass retrieved health data into the generation model
retrieved_data = result.iloc[0].to_dict()  # Convert the first result row to a dictionary
query = "genrate the story ?"
response = generate_response(retrieved_data, query)
print(response)

'Patient_Number': 9.0, 'Blood_Pressure_Abnormality': 0.0, 'Level_of_Hemoglobin': 10.88, 'Genetic_Pedigree_Coefficient': 1.0, 'Age': 72.0, 'BMI': 44.0, 'Sex': 0.0, 'Smoking': 0.0,'salt_content_in_

**4. On-the-fly Data Joining**

In [80]:
# Function to retrieve and join data from both datasets
def join_health_data(patient_id):
    health_record = df_health_1[df_health_1['Patient_Number'] == patient_id]
    activity_record = df_health_2[df_health_2['Patient_Number'] == patient_id]

    if not health_record.empty and not activity_record.empty:
        return pd.concat([health_record.reset_index(drop=True), activity_record.reset_index(drop=True)], axis=1)
    return None

In [81]:
join_health_data(1)

,Patient_Number,Blood_Pressure_Abnormality,Level_of_Hemoglobin,Genetic_Pedigree_Coefficient,Age,BMI,Sex,Pregnancy,Smoking,salt_content_in_the_diet,alcohol_consumption_per_day,Level_of_Stress,Chronic_kidney_disease,Adrenal_and_thyroid_disorders,Patient_Number,Day_Number,Physical_activity
0,1.0,1.0,11.28,1.0,34.0,23.0,1.0,1.0,0.0,48071.0,0.0,2.0,1.0,1.0,1,1,23590.000000
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,10411.000000
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,7815.000000
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,12366.000000
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5,23295.888889
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,30319.000000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7,46225.000000
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,8,40988.000000
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9,10540.000000
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10,27409.000000

**5. Evaluation:**

In [ ]:
from nltk.translate.bleu_score import sentence_bleu

reference = "This individual has high blood pressure and is at risk due to high BMI and smoking."

# Evaluate generated response
score = sentence_bleu([reference.split()], response.split())
print(f"BLEU score: {score}")

**6. Web Interface:**

In [ ]:
!pip install streamlit
import streamlit as st

# Streamlit interface for querying the RAG model
st.title("Health Data Analysis using RAG")

query = st.text_input("Enter your health-related query:")
patient_id = st.number_input("Enter Patient ID:", min_value=1, max_value=2000)

if st.button("Get Insights"):
    # Join the data and generate a response
    joined_data = join_health_data(patient_id)
    if joined_data is not None:
        response = generate_response(joined_data.iloc[0].to_dict(), query)
        st.write("Generated Insight:", response)
    else:
        st.write("Patient data not found.")

**7. Ethical Considerations**

In [ ]:
import hashlib
# Hashing sensitive data for privacy
df_health_1['Patient_Number'] = df_health_1['Patient_Number'].apply(lambda x: hashlib.sha256(str(x).encode()).hexdigest())